version: '3'
services:
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/uploads
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: hackharvard
